---
title: "ECMO_Sepsis_HTML"
author: "Sun Kim"
date: '2021 2 2 '
#output: powerpoint_presentation
output: html_document
---

```{r global_options, echo = FALSE, include = FALSE,warning = FALSE, message = FALSE}
options(width = 999)
knitr::opts_chunk$set(echo = F,message=F,comment=NA)
Sys.setlocale(category = "LC_CTYPE", locale = "ko_KR.UTF-8")
```

# Initialize
```{r results = 'asis'}
source("R_script/00_Initialize.R")
source("R_script/99_Output.R")
myt_output='HTML'
```
# Inclusion
```{r result='asis'}
library(kableExtra)

anal_data<-anal_data%>%
  filter(Group!=1)
ex_table[[5]]<-list(anal_data%>%count()%>%.$n,0,'preECMO sepsis 제외')
ex_table[[5]][2]<-ex_table[[4]][[1]]-ex_table[[5]][[1]]

ex_table<-do.call(rbind,ex_table)%>%data.frame()
names(ex_table)<-c('Result','Exclusion','Comment')

ex_table%>%kable()%>%
    kable_styling()
```

# Tables

```{r results = 'asis'}
source("R_script/06_Make_Table.R")
table1%>%print_mytable()
table2%>%print_mytable()
table3%>%print_mytable()
table4%>%print_mytable()
table5
```
# Analysis
```{r results = 'asis'}
source("R_script/07_Analysis.R")
extractOR(MV_LR_res)%>%knitr::kable(format = 'pipe')%>%print()
ORplot(MV_LR_res,type=2,show.CI = T)

ren_MV_LR_res<-MV_LR_res
names(ren_MV_LR_res$coefficients)<-c('(Intercept)','VV-ECMO','ECPR','Lactate at 24hr','CRRT','BSI')#,'UTI')

extractOR(ren_MV_LR_res)%>%knitr::kable(format = 'pipe')%>%print()
ORplot(ren_MV_LR_res,type=2,show.CI = T)


Surv_plot
UV_COX_res%>%knitr::kable(format = 'pipe')%>%print()
HRplot(UV_COX_res,type=2,show.CI=TRUE)

extractHR(MV_COX_res)%>%knitr::kable(format = 'pipe')%>%print()
HRplot(MV_COX_res)


ren_MV_COX_res<-MV_COX_res
ren_MV_COX_res$coefficient
names(ren_MV_COX_res$coefficients)<-c('BSI','ECPR','Age',
                                      #'Malignancy',
                                      'LDH','BUN',
                                      #'CRP',
                                      'Segmented neutrophil','Lactate at 24hr','CRRT','VV-ECMO')
extractHR(ren_MV_COX_res)%>%knitr::kable(format = 'pipe')%>%print()
HRplot(ren_MV_COX_res)


```


# Biomarker study
```{r results = 'asis'}
source("R_script/08_BSI_and_biomarker.R")
table6%>%print_mytable()
table7%>%print_mytable()
```

